import type { Calculator, CalculatorCategory } from './types'

import {
  percentOf,
  whatPercent,
  discount,
  markup,
  percentChange,
  commission,
} from './calculators/percentage'

import {
  simpleInterest,
  compoundInterest,
  rateConverter,
  presentValue,
  futureValue,
} from './calculators/interest'

import { priceTable } from './calculators/financing'

import { cdb, compoundGrowth } from './calculators/investment'

import { roi, breakEven, npvCalc, irrCalc } from './calculators/business'

import { inss, irpf, fgts } from './calculators/tax'

export const calculatorRegistry: Record<string, Calculator> = {
  // ===== PERCENTAGE =====
  'percent-of': {
    meta: {
      id: 'percent-of',
      name: 'Porcentagem de um valor',
      description: 'Calcula quanto é X% de um valor Y',
      category: 'percentage',
      params: [
        {
          key: 'x',
          label: 'Porcentagem (%)',
          type: 'number',
          description: 'O percentual a ser aplicado',
          defaultValue: 10,
          required: true,
          step: 0.1,
          suffix: '%',
        },
        {
          key: 'y',
          label: 'Valor base',
          type: 'number',
          description: 'O valor sobre o qual a porcentagem será calculada',
          defaultValue: 1000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
      ],
      keywords: ['porcentagem', 'percentual', 'cálculo', 'quanto é', 'percent'],
      formula: '(X / 100) × Y',
    },
    calc: percentOf,
  },

  'what-percent': {
    meta: {
      id: 'what-percent',
      name: 'Um valor representa quantos %',
      description: 'Calcula qual porcentagem um valor Y representa de um total X',
      category: 'percentage',
      params: [
        {
          key: 'x',
          label: 'Valor total',
          type: 'number',
          description: 'O valor total (100%)',
          defaultValue: 1000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'y',
          label: 'Valor parcial',
          type: 'number',
          description: 'O valor que você quer saber a porcentagem',
          defaultValue: 250,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
      ],
      keywords: ['porcentagem', 'percentual', 'representa', 'proporção', 'qual percentual'],
      formula: '(Y / X) × 100',
    },
    calc: whatPercent,
  },

  discount: {
    meta: {
      id: 'discount',
      name: 'Calculadora de desconto',
      description: 'Calcula o preço final após aplicar um desconto percentual',
      category: 'percentage',
      params: [
        {
          key: 'original',
          label: 'Preço original',
          type: 'number',
          description: 'Valor antes do desconto',
          defaultValue: 1000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'discountPct',
          label: 'Desconto (%)',
          type: 'number',
          description: 'Percentual de desconto',
          defaultValue: 15,
          required: true,
          step: 0.1,
          suffix: '%',
        },
      ],
      keywords: ['desconto', 'promoção', 'preço', 'economia', 'liquidação', 'off'],
      formula: 'Original × (1 - Desconto / 100)',
    },
    calc: discount,
  },

  markup: {
    meta: {
      id: 'markup',
      name: 'Markup e margem de lucro',
      description: 'Calcula o preço de venda a partir do custo aplicando um markup',
      category: 'percentage',
      params: [
        {
          key: 'cost',
          label: 'Custo do produto',
          type: 'number',
          description: 'Custo de aquisição ou produção',
          defaultValue: 100,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'markupPct',
          label: 'Markup (%)',
          type: 'number',
          description: 'Percentual de markup sobre o custo',
          defaultValue: 50,
          required: true,
          step: 0.1,
          suffix: '%',
        },
      ],
      keywords: ['markup', 'margem', 'lucro', 'preço de venda', 'precificação', 'custo'],
      formula: 'Custo × (1 + Markup / 100)',
    },
    calc: markup,
  },

  'percent-change': {
    meta: {
      id: 'percent-change',
      name: 'Variação percentual',
      description: 'Calcula a variação percentual entre dois valores',
      category: 'percentage',
      params: [
        {
          key: 'from',
          label: 'Valor inicial',
          type: 'number',
          description: 'Valor de referência (antes)',
          defaultValue: 100,
          required: true,
          step: 0.01,
        },
        {
          key: 'to',
          label: 'Valor final',
          type: 'number',
          description: 'Valor após a mudança (depois)',
          defaultValue: 120,
          required: true,
          step: 0.01,
        },
      ],
      keywords: ['variação', 'mudança', 'crescimento', 'aumento', 'redução', 'delta'],
      formula: '((Final - Inicial) / Inicial) × 100',
    },
    calc: percentChange,
  },

  commission: {
    meta: {
      id: 'commission',
      name: 'Calculadora de comissão',
      description: 'Calcula o valor da comissão sobre vendas',
      category: 'percentage',
      params: [
        {
          key: 'salesAmount',
          label: 'Total de vendas',
          type: 'number',
          description: 'Valor total das vendas realizadas',
          defaultValue: 10000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'commissionRate',
          label: 'Taxa de comissão (%)',
          type: 'number',
          description: 'Percentual de comissão sobre as vendas',
          defaultValue: 5,
          required: true,
          step: 0.1,
          suffix: '%',
        },
      ],
      keywords: ['comissão', 'vendas', 'vendedor', 'remuneração', 'comission'],
      formula: 'Vendas × (Taxa / 100)',
    },
    calc: commission,
  },

  // ===== INTEREST =====
  'simple-interest': {
    meta: {
      id: 'simple-interest',
      name: 'Juros Simples',
      description: 'Calcula juros simples: o rendimento incide apenas sobre o principal',
      category: 'interest',
      params: [
        {
          key: 'principal',
          label: 'Capital inicial',
          type: 'number',
          description: 'Valor investido ou emprestado',
          defaultValue: 10000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de juros (% a.p.)',
          type: 'number',
          description: 'Taxa de juros por período',
          defaultValue: 5,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'time',
          label: 'Períodos',
          type: 'number',
          description: 'Número de períodos (meses, anos, etc.)',
          defaultValue: 12,
          required: true,
          step: 1,
        },
      ],
      keywords: ['juros simples', 'rendimento', 'linear', 'capital', 'simples'],
      formula: 'Montante = Principal × (1 + Taxa × Tempo)',
    },
    calc: simpleInterest,
  },

  'compound-interest': {
    meta: {
      id: 'compound-interest',
      name: 'Juros Compostos',
      description: 'Calcula juros compostos: juros sobre juros conforme a frequência de capitalização',
      category: 'interest',
      params: [
        {
          key: 'principal',
          label: 'Capital inicial',
          type: 'number',
          description: 'Valor investido ou emprestado',
          defaultValue: 10000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de juros (% a.a.)',
          type: 'number',
          description: 'Taxa de juros anual',
          defaultValue: 12,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'time',
          label: 'Período (anos)',
          type: 'number',
          description: 'Duração em anos',
          defaultValue: 3,
          required: true,
          step: 0.5,
        },
        {
          key: 'frequency',
          label: 'Capitalizações por ano',
          type: 'select',
          description: 'Frequência de capitalização dos juros',
          defaultValue: 12,
          required: true,
          options: [
            { value: '1', label: 'Anual (1×)' },
            { value: '2', label: 'Semestral (2×)' },
            { value: '4', label: 'Trimestral (4×)' },
            { value: '12', label: 'Mensal (12×)' },
            { value: '252', label: 'Diária útil (252×)' },
            { value: '360', label: 'Diária (360×)' },
          ],
        },
      ],
      keywords: ['juros compostos', 'composto', 'capitalização', 'exponencial', 'juros sobre juros'],
      formula: 'Montante = Principal × (1 + Taxa / n)^(n × t)',
    },
    calc: compoundInterest,
  },

  'rate-converter': {
    meta: {
      id: 'rate-converter',
      name: 'Conversor de taxas equivalentes',
      description: 'Converte taxas de juros entre diferentes períodos de capitalização',
      category: 'interest',
      params: [
        {
          key: 'rate',
          label: 'Taxa conhecida (%)',
          type: 'number',
          description: 'Taxa de juros que você conhece',
          defaultValue: 12,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'fromPeriods',
          label: 'Períodos da taxa original',
          type: 'select',
          description: 'Número de períodos por ano da taxa original',
          defaultValue: 12,
          required: true,
          options: [
            { value: '1', label: 'Anual' },
            { value: '2', label: 'Semestral' },
            { value: '4', label: 'Trimestral' },
            { value: '12', label: 'Mensal' },
            { value: '252', label: 'Diária (dias úteis)' },
            { value: '360', label: 'Diária' },
          ],
        },
        {
          key: 'toPeriods',
          label: 'Períodos da taxa desejada',
          type: 'select',
          description: 'Número de períodos por ano da taxa que deseja obter',
          defaultValue: 1,
          required: true,
          options: [
            { value: '1', label: 'Anual' },
            { value: '2', label: 'Semestral' },
            { value: '4', label: 'Trimestral' },
            { value: '12', label: 'Mensal' },
            { value: '252', label: 'Diária (dias úteis)' },
            { value: '360', label: 'Diária' },
          ],
        },
      ],
      keywords: ['taxa equivalente', 'conversão', 'taxa', 'equivalência', 'converter taxa'],
      formula: 'Taxa_eq = (1 + Taxa)^(Períodos_desejados / Períodos_originais) - 1',
    },
    calc: rateConverter,
  },

  'present-value': {
    meta: {
      id: 'present-value',
      name: 'Valor Presente (VP)',
      description: 'Calcula quanto vale hoje um valor futuro, considerando uma taxa de desconto',
      category: 'interest',
      params: [
        {
          key: 'futureValue',
          label: 'Valor futuro',
          type: 'number',
          description: 'Valor que será recebido no futuro',
          defaultValue: 50000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de desconto (% a.p.)',
          type: 'number',
          description: 'Taxa de desconto por período',
          defaultValue: 10,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'periods',
          label: 'Períodos',
          type: 'number',
          description: 'Número de períodos até o recebimento',
          defaultValue: 5,
          required: true,
          step: 1,
        },
      ],
      keywords: ['valor presente', 'VP', 'desconto', 'PV', 'present value', 'trazido a valor presente'],
      formula: 'VP = VF / (1 + Taxa)^Períodos',
    },
    calc: presentValue,
  },

  'future-value': {
    meta: {
      id: 'future-value',
      name: 'Valor Futuro (VF)',
      description: 'Calcula o valor futuro de um investimento com juros compostos',
      category: 'interest',
      params: [
        {
          key: 'presentValue',
          label: 'Valor presente',
          type: 'number',
          description: 'Valor investido hoje',
          defaultValue: 10000,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de juros (% a.p.)',
          type: 'number',
          description: 'Taxa de juros por período',
          defaultValue: 8,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'periods',
          label: 'Períodos',
          type: 'number',
          description: 'Número de períodos de capitalização',
          defaultValue: 10,
          required: true,
          step: 1,
        },
      ],
      keywords: ['valor futuro', 'VF', 'FV', 'future value', 'capitalização', 'projeção'],
      formula: 'VF = VP × (1 + Taxa)^Períodos',
    },
    calc: futureValue,
  },

  // ===== FINANCING =====
  'price-table': {
    meta: {
      id: 'price-table',
      name: 'Tabela de Financiamento (PRICE/SAC)',
      description: 'Simula um financiamento com tabela PRICE (prestações fixas) ou SAC (amortização constante)',
      category: 'financing',
      params: [
        {
          key: 'amount',
          label: 'Valor financiado',
          type: 'number',
          description: 'Valor total do financiamento',
          defaultValue: 200000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de juros (% a.a.)',
          type: 'number',
          description: 'Taxa de juros anual',
          defaultValue: 12,
          required: true,
          step: 0.01,
          suffix: '%',
        },
        {
          key: 'months',
          label: 'Prazo (meses)',
          type: 'number',
          description: 'Número de parcelas',
          defaultValue: 360,
          required: true,
          step: 12,
        },
        {
          key: 'system',
          label: 'Sistema de amortização',
          type: 'select',
          description: 'PRICE = prestações fixas | SAC = amortização constante',
          defaultValue: 0,
          required: true,
          options: [
            { value: '0', label: 'PRICE (prestações fixas)' },
            { value: '1', label: 'SAC (amortização constante)' },
          ],
        },
      ],
      keywords: ['financiamento', 'tabela', 'PRICE', 'SAC', 'amortização', 'prestação', 'parcela', 'imóvel'],
      formula: 'PRICE: PMT = PV × [i(1+i)^n] / [(1+i)^n - 1]  |  SAC: Amort = PV / n',
    },
    calc: priceTable,
  },

  // ===== INVESTMENT =====
  cdb: {
    meta: {
      id: 'cdb',
      name: 'CDB / Renda Fixa',
      description: 'Simula investimento em CDB com rendimento atrelado ao CDI e IR regressivo',
      category: 'investment',
      params: [
        {
          key: 'initial',
          label: 'Aporte inicial',
          type: 'number',
          description: 'Valor investido inicialmente',
          defaultValue: 10000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'monthlyDeposit',
          label: 'Aporte mensal',
          type: 'number',
          description: 'Valor depositado todo mês',
          defaultValue: 500,
          required: true,
          step: 50,
          prefix: 'R$',
        },
        {
          key: 'cdiPct',
          label: '% do CDI',
          type: 'number',
          description: 'Rentabilidade como percentual do CDI (ex: 100% CDI, 110% CDI)',
          defaultValue: 100,
          required: true,
          step: 1,
          suffix: '%',
        },
        {
          key: 'months',
          label: 'Prazo (meses)',
          type: 'number',
          description: 'Período do investimento em meses',
          defaultValue: 24,
          required: true,
          step: 1,
        },
      ],
      keywords: ['CDB', 'renda fixa', 'CDI', 'investimento', 'IR', 'imposto de renda', 'tributação'],
      formula: 'Montante = Σ Aportes × (1 + CDI × %CDI)^t - IR',
    },
    calc: cdb,
  },

  'compound-growth': {
    meta: {
      id: 'compound-growth',
      name: 'Crescimento composto',
      description: 'Simula o crescimento de um investimento com aportes mensais e juros compostos',
      category: 'investment',
      params: [
        {
          key: 'initial',
          label: 'Aporte inicial',
          type: 'number',
          description: 'Valor investido inicialmente',
          defaultValue: 5000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'monthly',
          label: 'Aporte mensal',
          type: 'number',
          description: 'Valor depositado todo mês',
          defaultValue: 1000,
          required: true,
          step: 50,
          prefix: 'R$',
        },
        {
          key: 'rate',
          label: 'Taxa de juros (% a.a.)',
          type: 'number',
          description: 'Taxa de rentabilidade anual',
          defaultValue: 10,
          required: true,
          step: 0.1,
          suffix: '%',
        },
        {
          key: 'years',
          label: 'Período (anos)',
          type: 'number',
          description: 'Duração do investimento em anos',
          defaultValue: 10,
          required: true,
          step: 1,
        },
      ],
      keywords: ['crescimento', 'aportes', 'investimento', 'longo prazo', 'acumulação', 'juros compostos'],
      formula: 'Montante = Inicial × (1+i)^n + PMT × [(1+i)^n - 1] / i',
    },
    calc: compoundGrowth,
  },

  // ===== BUSINESS =====
  roi: {
    meta: {
      id: 'roi',
      name: 'ROI — Retorno sobre Investimento',
      description: 'Calcula o retorno percentual sobre um investimento',
      category: 'business',
      params: [
        {
          key: 'invested',
          label: 'Valor investido',
          type: 'number',
          description: 'Capital total investido',
          defaultValue: 50000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'returned',
          label: 'Valor retornado',
          type: 'number',
          description: 'Montante total recebido de volta',
          defaultValue: 65000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
      ],
      keywords: ['ROI', 'retorno', 'investimento', 'lucratividade', 'payback'],
      formula: 'ROI = ((Retornado - Investido) / Investido) × 100',
    },
    calc: roi,
  },

  'break-even': {
    meta: {
      id: 'break-even',
      name: 'Ponto de Equilíbrio',
      description: 'Calcula quantas unidades precisam ser vendidas para cobrir todos os custos',
      category: 'business',
      params: [
        {
          key: 'fixedCosts',
          label: 'Custos fixos',
          type: 'number',
          description: 'Custos fixos totais (aluguel, salários, etc.)',
          defaultValue: 10000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'unitPrice',
          label: 'Preço unitário',
          type: 'number',
          description: 'Preço de venda por unidade',
          defaultValue: 150,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
        {
          key: 'unitVariableCost',
          label: 'Custo variável unitário',
          type: 'number',
          description: 'Custo variável por unidade produzida/vendida',
          defaultValue: 70,
          required: true,
          step: 0.01,
          prefix: 'R$',
        },
      ],
      keywords: ['ponto de equilíbrio', 'breakeven', 'break even', 'custos', 'lucro zero'],
      formula: 'PE = Custos Fixos / (Preço - Custo Variável)',
    },
    calc: breakEven,
  },

  npv: {
    meta: {
      id: 'npv',
      name: 'VPL — Valor Presente Líquido',
      description: 'Calcula o valor presente líquido de uma série de fluxos de caixa',
      category: 'business',
      params: [
        {
          key: 'rate',
          label: 'Taxa de desconto (% a.p.)',
          type: 'number',
          description: 'Taxa de desconto por período (TMA)',
          defaultValue: 10,
          required: true,
          step: 0.1,
          suffix: '%',
        },
        {
          key: 'cf0',
          label: 'Fluxo inicial (t=0)',
          type: 'number',
          description: 'Investimento inicial (valor negativo)',
          defaultValue: -50000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf1',
          label: 'Fluxo ano 1',
          type: 'number',
          description: 'Fluxo de caixa no período 1',
          defaultValue: 15000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf2',
          label: 'Fluxo ano 2',
          type: 'number',
          description: 'Fluxo de caixa no período 2',
          defaultValue: 20000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf3',
          label: 'Fluxo ano 3',
          type: 'number',
          description: 'Fluxo de caixa no período 3',
          defaultValue: 25000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf4',
          label: 'Fluxo ano 4',
          type: 'number',
          description: 'Fluxo de caixa no período 4',
          defaultValue: 30000,
          required: false,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf5',
          label: 'Fluxo ano 5',
          type: 'number',
          description: 'Fluxo de caixa no período 5',
          defaultValue: 0,
          required: false,
          step: 100,
          prefix: 'R$',
        },
      ],
      keywords: ['VPL', 'NPV', 'valor presente líquido', 'fluxo de caixa', 'viabilidade', 'TMA'],
      formula: 'VPL = Σ (FCt / (1 + Taxa)^t)',
    },
    calc: npvCalc,
  },

  irr: {
    meta: {
      id: 'irr',
      name: 'TIR — Taxa Interna de Retorno',
      description: 'Calcula a taxa de retorno que zera o VPL de uma série de fluxos de caixa',
      category: 'business',
      params: [
        {
          key: 'cf0',
          label: 'Fluxo inicial (t=0)',
          type: 'number',
          description: 'Investimento inicial (valor negativo)',
          defaultValue: -50000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf1',
          label: 'Fluxo ano 1',
          type: 'number',
          description: 'Fluxo de caixa no período 1',
          defaultValue: 15000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf2',
          label: 'Fluxo ano 2',
          type: 'number',
          description: 'Fluxo de caixa no período 2',
          defaultValue: 20000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf3',
          label: 'Fluxo ano 3',
          type: 'number',
          description: 'Fluxo de caixa no período 3',
          defaultValue: 25000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf4',
          label: 'Fluxo ano 4',
          type: 'number',
          description: 'Fluxo de caixa no período 4',
          defaultValue: 30000,
          required: false,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'cf5',
          label: 'Fluxo ano 5',
          type: 'number',
          description: 'Fluxo de caixa no período 5',
          defaultValue: 0,
          required: false,
          step: 100,
          prefix: 'R$',
        },
      ],
      keywords: ['TIR', 'IRR', 'taxa interna de retorno', 'retorno', 'viabilidade', 'investimento'],
      formula: '0 = Σ (FCt / (1 + TIR)^t) — resolvido por Newton-Raphson',
    },
    calc: irrCalc,
  },

  // ===== TAX =====
  inss: {
    meta: {
      id: 'inss',
      name: 'INSS 2024',
      description: 'Calcula o desconto do INSS sobre o salário conforme a tabela progressiva de 2024',
      category: 'tax',
      params: [
        {
          key: 'salary',
          label: 'Salário bruto',
          type: 'number',
          description: 'Salário bruto mensal',
          defaultValue: 5000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
      ],
      keywords: ['INSS', 'previdência', 'salário', 'desconto', 'contribuição', '2024'],
      formula: 'INSS = Σ (Faixa × Alíquota) — progressivo, teto de R$908,85',
    },
    calc: inss,
  },

  irpf: {
    meta: {
      id: 'irpf',
      name: 'IRPF 2024',
      description: 'Calcula o Imposto de Renda Pessoa Física mensal conforme a tabela progressiva de 2024',
      category: 'tax',
      params: [
        {
          key: 'salary',
          label: 'Salário bruto',
          type: 'number',
          description: 'Salário bruto mensal',
          defaultValue: 8000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
        {
          key: 'dependents',
          label: 'Nº de dependentes',
          type: 'number',
          description: 'Quantidade de dependentes para dedução (R$189,59 cada)',
          defaultValue: 0,
          required: false,
          step: 1,
        },
        {
          key: 'deductions',
          label: 'Outras deduções',
          type: 'number',
          description: 'Pensão alimentícia, previdência privada, etc.',
          defaultValue: 0,
          required: false,
          step: 1,
          prefix: 'R$',
        },
      ],
      keywords: ['IRPF', 'imposto de renda', 'IR', 'salário', 'leão', 'tributação', '2024'],
      formula: 'IRPF = (Salário - INSS - Dependentes×R$189,59 - Deduções) × Alíquota - Parcela a deduzir',
    },
    calc: irpf,
  },

  fgts: {
    meta: {
      id: 'fgts',
      name: 'FGTS',
      description: 'Calcula o depósito mensal e anual do FGTS (8% sobre o salário)',
      category: 'tax',
      params: [
        {
          key: 'salary',
          label: 'Salário bruto',
          type: 'number',
          description: 'Salário bruto mensal',
          defaultValue: 5000,
          required: true,
          step: 100,
          prefix: 'R$',
        },
      ],
      keywords: ['FGTS', 'fundo de garantia', 'depósito', 'trabalhista', 'CLT', '8%'],
      formula: 'FGTS = Salário × 8%',
    },
    calc: fgts,
  },
}

export const calculatorsByCategory: Record<CalculatorCategory, Calculator[]> = {
  percentage: [],
  interest: [],
  financing: [],
  investment: [],
  business: [],
  tax: [],
  converter: [],
  statistics: [],
}

for (const calc of Object.values(calculatorRegistry)) {
  const cat = calc.meta.category
  if (calculatorsByCategory[cat]) {
    calculatorsByCategory[cat].push(calc)
  }
}

export const calculatorList: Calculator[] = Object.values(calculatorRegistry)
